#!/bin/bash

if [ $# -lt "2" ]; then
  echo "Requires 2 params (ticket # and change description)"
  exit 1
fi

function extract-field {
  echo "$1" | sed '/'"$2"'/!d;s/'"$2"': \(.*\)/\1/'
}

svninfo=`svn info`
rev=`extract-field "$svninfo" "Revision"`
ticket=$1
shift
desc=$1
shift
svn diff "$@" > ~/OpenLayers/olpatches/t${ticket}r${rev}.${desc}.patch

