#!/bin/bash
# Play a stream with mplayer, outputting IceCast track titles to status bar
play="▶"

# Executes each new track with "artist" "track", and with no args on exit.
scrobble_cmd="scrobble"

on_exit () {
  xmobar-msg
  $scrobble_cmd
}
trap on_exit EXIT

on_int () {
  on_exit
  kill 0
}
trap on_int INT

stream=${1:-"http://sfstream1.somafm.com:3000"}
echo "Playing $stream"

output_track_title () {
  sed -nu "s/.*StreamTitle='\(.\+\)';.\+/$play \1/p" \
  | tee ~/.xmobarmsg.fifo \
  | sed -nu "s/$play //p" \
  | tee /dev/tty \
  | sed -nu "s/\(.*\) - \(.*\)/\"\1\" \"\2\"\n/p" \
  | xargs -L 1 $scrobble_cmd
}

#mplayer $stream | tee /dev/stderr | output_track_title
mplayer -allow-dangerous-playlist-parsing $stream 2>/dev/null | output_track_title
