#!/bin/bash
TEXT=$(echo | dmenu)
if [ -n "$TEXT" ]; then
  echo "$TEXT" > ~/.screensaver-text
else
  rm ~/.screensaver-text
fi
# Phosphorous is currently line #80 in programs section of ~/.xscreensaver
xscreensaver-command -select 80

