#!/bin/bash
stations=(\
  7soul130 \
  bagel64 \
  beatblender64 \
  bootliquor130 \
  brfm130 \
  cliqhop64 \
  covers64 \
  deepspaceone130 \
  defcon64 \
  digitalis130 \
  doomed64 \
  dronezone130 \
  dubstep64 \
  earwaves130 \
  fluid130 \
  folkfwd64 \
  groovesalad130 \
  illstreet130 \
  indiepop130 \
  lush130 \
  metal130 \
  missioncontrol64 \
  poptron64 \
  secretagent130 \
  seventies64 \
  sf103364 \
  silent130 \
  sonicuniverse64 \
  spacestation130 \
  suburbsofgoa130 \
  sxfm64 \
  thetrip64 \
  thistle64 \
  u80s130 \
)

help () {
  echo "Available stations:"
  echo ${stations[*]}
}

if [ -n "${COMP_LINE}" ]
then
    compgen -W "${stations[*]} --help -h" -- ${COMP_LINE##* }
    exit
fi

case "$1" in
  --help | -h)
    help
    exit
    ;;
esac

if [ -z "$1" ]
then
  num_stations=${#stations[*]}
  station=${stations[$((RANDOM % num_stations))]}
else
  station=$1
fi

radio http://somafm.com/${station}.pls
